= Hardware specifications

Where did your run your tests? A laptop, or goldengate?

 on goldengate

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

 64 processors
 CPU speed of 1200.060 MHz
 95320 mebibytes of RAM 

= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?

 The first printf() statement must be calling malloc internally (to store the string value). 

Why is the value 1040 bytes?

 printf() calls malloc(1024) to store its string and our malloc function gives it 1024 + 16 bytes for the chunk metadata, so 1040 bytes total.

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.

 At the end of the program, 116 bytes have been allocated.  This makes sense because we allocated 100 bytes every time, and the first call to our malloc() function gave us 116 bytes (100 + 16 bytes for the "chunk" metadata).  Freeing this memory adds it to the free list and subsequent calls to malloc(100) reuse the same chunk of memory from the free list. 

= Fragmentation

 Fragmentation is when there are chunks of allocated memory are not being used.  Internal fragmentation is when there are unused bytes of memory within a block of memory being used (i.e. only some of the memory in the block is actually in use).  External fragmentation is when there are a lot of unused/free chunks of memory not being used (i.e. blocks of memory in the free list).

 Output of benchmark2 using fragstats:

 The initial top of the heap is 0x7f7a18036000.
 Total blocks: 161, Free: 103, Used: 58
 Internal unused: total: 178682, average: 3080.72, smallest: 511, largest: 3979
 External unused: total: 144345, average: 1401.41, smallest: 10, largest: 3984
 0
 The current top of the heap is 0x7f7a1808c527.
 Increased by 345 (0x159) Kbyte
 Total blocks: 167, Free: 113, Used: 54
 Internal unused: total: 159454, average: 2952.85, smallest: 107, largest: 3991
 External unused: total: 177549, average: 1571.23, smallest: 10, largest: 3984
 1
 The current top of the heap is 0x7f7a18092327.
 Increased by 368 (0x170) Kbyte
 Total blocks: 169, Free: 117, Used: 52
 Internal unused: total: 157088, average: 3020.92, smallest: 129, largest: 3977
 External unused: total: 189341, average: 1618.30, smallest: 10, largest: 3997
 2
 The current top of the heap is 0x7f7a18094282.
 Increased by 376 (0x178) Kbyte
 Total blocks: 172, Free: 120, Used: 52
 Internal unused: total: 160672, average: 3089.85, smallest: 146, largest: 3989
 External unused: total: 201235, average: 1676.96, smallest: 10, largest: 3998
 3
 The current top of the heap is 0x7f7a18097188.
 Increased by 388 (0x184) Kbyte
 Total blocks: 175, Free: 125, Used: 50
 Internal unused: total: 145974, average: 2919.48, smallest: 6, largest: 3984
 External unused: total: 222205, average: 1777.64, smallest: 10, largest: 3999
 4
 The current top of the heap is 0x7f7a1809a095.
 Increased by 400 (0x190) Kbyte
 Total blocks: 176, Free: 116, Used: 60
 Internal unused: total: 191611, average: 3193.52, smallest: 984, largest: 3986
 External unused: total: 189140, average: 1630.52, smallest: 10, largest: 3999
 5
 The current top of the heap is 0x7f7a1809b045.
 Increased by 404 (0x194) Kbyte
 Total blocks: 176, Free: 128, Used: 48
 Internal unused: total: 153391, average: 3195.65, smallest: 381, largest: 3991
 External unused: total: 227231, average: 1775.24, smallest: 10, largest: 4000
 6
 The current top of the heap is 0x7f7a1809b045.
 Increased by 404 (0x194) Kbyte
 Total blocks: 177, Free: 125, Used: 52
 Internal unused: total: 154837, average: 2977.63, smallest: 138, largest: 3989
 External unused: total: 219943, average: 1759.54, smallest: 10, largest: 3999
 7
 The current top of the heap is 0x7f7a1809bff5.
 Increased by 407 (0x197) Kbyte
 Total blocks: 178, Free: 118, Used: 60
 Internal unused: total: 193404, average: 3223.40, smallest: 401, largest: 3990
 External unused: total: 193697, average: 1641.50, smallest: 10, largest: 4000
 8
 The current top of the heap is 0x7f7a1809cfa5.
 Increased by 411 (0x19b) Kbyte
 Total blocks: 178, Free: 130, Used: 48
 Internal unused: total: 150237, average: 3129.94, smallest: 636, largest: 3987
 External unused: total: 237661, average: 1828.16, smallest: 10, largest: 4000
 9
 The current top of the heap is 0x7f7a1809cfa5.
 Increased by 411 (0x19b) Kbyte 
